version: '3.8'

services:
  web:
    build: ./Diccionarr
    ports:
      - "8080:80"
    volumes:
      - ./Diccionarr:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: diccionario
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./Diccionarr/diccionario.sql:/docker-entrypoint-initdb.d/diccionario.sql

volumes:
  db_data: